### ISSUE TITLE
[Bug] Resource Page - Fix Welcome Paragraph Bug

### ISSUE THREAD

**Issue by justsanchez** [justsanchez/FESonline#47]
As of right now [Mobile], the welcome paragraph could use some mobile styling and is allowing the user to horizontally scroll. Ill attach a link to a doc to test on mobile using ngrok (i recommend using chrome when using ngrok for testing static web pages)

https://docs.google.com/document/d/1mwPEWv7mfG0UGfOEeMfT2h3VgUyfni5VwjBKzcV_A0I/edit

In the _resourcesStylesheet.css_, touch this up and add a media query if needed
```CSS
.welcomeParagraph {
    color: #fff;
    font-size: large;
    margin: 0 27% 40px;  /*This might be causing the issue*/
    text-align: center;
    width: 50%;
    line-height: 1.6;
}
```
![IMG_0537](https://github.com/user-attachments/assets/fd4a9e11-524e-42c7-90e5-de8f5148b6ea)
